//! Typed payload layout for generated verifier artifacts.
//!
//! This is the small, local piece we borrow from the reusable-artifact style:
//! generated byte payloads should have one validated section map instead of
//! scattered offset arithmetic. The Solidity shape remains static and pinned.

#![allow(dead_code)]

use ruint::aliases::U256;

use crate::codegen::layout::{G1_WORDS, WORD_BYTES};

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum PayloadSectionKind {
    /// Fixed VK header words consumed by both embedded and external VK paths.
    Header,
    /// Deduplicated Fr constants used by the compact quotient VM.
    QuotientConstants,
    /// Packed compact-VM bytecode words.
    QuotientProgram,
    /// EIP-2537-padded fixed polynomial commitments.
    FixedCommitments,
    /// EIP-2537-padded permutation commitment bases.
    PermutationCommitments,
}

/// One contiguous word-aligned section inside the generated VK payload.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct PayloadSection {
    /// Logical section kind.
    pub(crate) kind: PayloadSectionKind,
    /// Start word relative to the beginning of the VK payload.
    pub(crate) word_offset: usize,
    /// Length in EVM words.
    pub(crate) word_len: usize,
}

impl PayloadSection {
    /// End word offset, exclusive.
    pub(crate) fn word_end(self) -> usize {
        self.word_offset + self.word_len
    }

    /// Start byte offset relative to the beginning of the VK payload.
    pub(crate) fn byte_offset(self) -> usize {
        self.word_offset * WORD_BYTES
    }

    /// Length in bytes.
    pub(crate) fn byte_len(self) -> usize {
        self.word_len * WORD_BYTES
    }
}

/// Monotonic section map for the generated VK byte payload.
///
/// The layout is append-only by construction so template emission, runtime
/// `extcodecopy`, and tests all agree on the same section boundaries.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub(crate) struct VkPayloadLayout {
    sections: Vec<PayloadSection>,
    cursor_words: usize,
}

impl VkPayloadLayout {
    /// Start an empty layout with the cursor at word zero.
    pub(crate) fn new() -> Self {
        Self::default()
    }

    /// Build the complete static VK payload section map.
    ///
    /// Commitment counts are converted into EIP-2537 G1 word widths here so
    /// callers do not repeat that arithmetic at the emission sites.
    pub(crate) fn for_vk(
        header_words: usize,
        quotient_const_words: usize,
        quotient_program_words: usize,
        fixed_commitments: usize,
        permutation_commitments: usize,
    ) -> Result<Self, String> {
        let mut layout = Self::new();
        layout.reserve(PayloadSectionKind::Header, header_words)?;
        layout.reserve(PayloadSectionKind::QuotientConstants, quotient_const_words)?;
        layout.reserve(PayloadSectionKind::QuotientProgram, quotient_program_words)?;
        layout.reserve_g1(PayloadSectionKind::FixedCommitments, fixed_commitments)?;
        layout.reserve_g1(
            PayloadSectionKind::PermutationCommitments,
            permutation_commitments,
        )?;
        layout.validate()?;
        Ok(layout)
    }

    /// Reserve a generic word section at the current cursor.
    ///
    /// Each logical kind may appear at most once; duplicate sections would make
    /// generated offsets ambiguous and are rejected immediately.
    pub(crate) fn reserve(
        &mut self,
        kind: PayloadSectionKind,
        word_len: usize,
    ) -> Result<PayloadSection, String> {
        if self.sections.iter().any(|section| section.kind == kind) {
            return Err(format!("duplicate VK payload section: {kind:?}"));
        }

        let section = PayloadSection {
            kind,
            word_offset: self.cursor_words,
            word_len,
        };
        self.cursor_words += word_len;
        self.sections.push(section);
        Ok(section)
    }

    /// Reserve a section containing `commitments` EIP-2537-padded G1 points.
    pub(crate) fn reserve_g1(
        &mut self,
        kind: PayloadSectionKind,
        commitments: usize,
    ) -> Result<PayloadSection, String> {
        self.reserve(kind, commitments * G1_WORDS)
    }

    /// Return the section for `kind`, if it has been reserved.
    pub(crate) fn section(&self, kind: PayloadSectionKind) -> Option<PayloadSection> {
        self.sections
            .iter()
            .copied()
            .find(|section| section.kind == kind)
    }

    /// Return the section for `kind` or an explanatory layout error.
    pub(crate) fn require_section(
        &self,
        kind: PayloadSectionKind,
    ) -> Result<PayloadSection, String> {
        self.section(kind)
            .ok_or_else(|| format!("missing VK payload section: {kind:?}"))
    }

    /// Start word of a required section.
    pub(crate) fn word_offset(&self, kind: PayloadSectionKind) -> Result<usize, String> {
        Ok(self.require_section(kind)?.word_offset)
    }

    /// Word length of a required section.
    pub(crate) fn word_len(&self, kind: PayloadSectionKind) -> Result<usize, String> {
        Ok(self.require_section(kind)?.word_len)
    }

    /// Start byte offset of a required section.
    pub(crate) fn byte_offset(&self, kind: PayloadSectionKind) -> Result<usize, String> {
        Ok(self.require_section(kind)?.byte_offset())
    }

    /// Byte length of a required section.
    pub(crate) fn byte_len(&self, kind: PayloadSectionKind) -> Result<usize, String> {
        Ok(self.require_section(kind)?.byte_len())
    }

    /// Total payload length in words.
    pub(crate) fn total_words(&self) -> usize {
        self.cursor_words
    }

    /// Total payload length in bytes.
    pub(crate) fn total_bytes(&self) -> usize {
        self.total_words() * WORD_BYTES
    }

    /// Check that sections are contiguous and the cursor matches their end.
    pub(crate) fn validate(&self) -> Result<(), String> {
        let mut cursor = 0usize;
        for section in &self.sections {
            if section.word_offset != cursor {
                return Err(format!(
                    "VK payload section {:?} starts at {:#x}, expected {cursor:#x}",
                    section.kind, section.word_offset
                ));
            }
            cursor = section.word_end();
        }
        if cursor != self.cursor_words {
            return Err(format!(
                "VK payload cursor mismatch: sections end at {cursor:#x}, cursor is {:#x}",
                self.cursor_words
            ));
        }
        Ok(())
    }
}

/// Codec for storing byte-oriented quotient programs in VK constant words.
pub(crate) struct PackedProgramCodec;

impl PackedProgramCodec {
    /// Number of EVM words required to hold `byte_len` bytes.
    pub(crate) fn word_len_for_bytes(byte_len: usize) -> usize {
        byte_len.div_ceil(WORD_BYTES)
    }

    /// Pack bytes into big-endian `U256` words, zero-padding the final word.
    pub(crate) fn encode_words(bytes: &[u8]) -> Vec<U256> {
        let mut padded = bytes.to_vec();
        padded.resize(Self::word_len_for_bytes(bytes.len()) * WORD_BYTES, 0);
        padded
            .chunks(WORD_BYTES)
            .map(U256::from_be_slice)
            .collect::<Vec<_>>()
    }

    /// Decode packed words and verify that all unused padding bytes are zero.
    pub(crate) fn decode_words(words: &[U256], byte_len: usize) -> Result<Vec<u8>, String> {
        let capacity = words.len() * WORD_BYTES;
        if byte_len > capacity {
            return Err(format!(
                "packed program byte length {byte_len} exceeds word capacity {capacity}"
            ));
        }

        let mut bytes = Vec::with_capacity(capacity);
        for word in words {
            bytes.extend_from_slice(&word.to_be_bytes::<32>());
        }

        if bytes[byte_len..].iter().any(|byte| *byte != 0) {
            return Err("packed program has non-zero padding bytes".to_string());
        }

        bytes.truncate(byte_len);
        Ok(bytes)
    }
}

#[cfg(test)]
mod tests {
    use super::{PackedProgramCodec, PayloadSectionKind, VkPayloadLayout};
    use ruint::aliases::U256;

    #[test]
    fn vk_payload_layout_reserves_monotonic_sections() {
        let layout = VkPayloadLayout::for_vk(31, 3, 5, 7, 2).unwrap();

        assert_eq!(layout.word_offset(PayloadSectionKind::Header).unwrap(), 0);
        assert_eq!(
            layout
                .word_offset(PayloadSectionKind::QuotientConstants)
                .unwrap(),
            31
        );
        assert_eq!(
            layout
                .word_offset(PayloadSectionKind::QuotientProgram)
                .unwrap(),
            34
        );
        assert_eq!(
            layout
                .word_offset(PayloadSectionKind::FixedCommitments)
                .unwrap(),
            39
        );
        assert_eq!(
            layout
                .word_offset(PayloadSectionKind::PermutationCommitments)
                .unwrap(),
            67
        );
        assert_eq!(layout.total_words(), 75);
        assert_eq!(
            layout
                .byte_offset(PayloadSectionKind::FixedCommitments)
                .unwrap(),
            39 * 0x20
        );
        assert_eq!(
            layout
                .byte_len(PayloadSectionKind::PermutationCommitments)
                .unwrap(),
            2 * 0x80
        );
    }

    #[test]
    fn vk_payload_layout_rejects_duplicate_sections() {
        let mut layout = VkPayloadLayout::new();
        layout
            .reserve(
                PayloadSectionKind::Header,
                crate::codegen::layout::VK_HEADER_WORDS,
            )
            .unwrap();
        let err = layout
            .reserve(PayloadSectionKind::Header, 1)
            .expect_err("duplicate section rejected");

        assert!(err.contains("duplicate VK payload section"));
    }

    #[test]
    fn packed_program_codec_round_trips_with_explicit_byte_len() {
        let bytes = (0..37u8).collect::<Vec<_>>();
        let words = PackedProgramCodec::encode_words(&bytes);

        assert_eq!(words.len(), 2);
        assert_eq!(
            PackedProgramCodec::decode_words(&words, bytes.len()).unwrap(),
            bytes
        );
    }

    #[test]
    fn packed_program_codec_rejects_length_past_capacity() {
        let words = PackedProgramCodec::encode_words(&[1, 2, 3]);
        let err = PackedProgramCodec::decode_words(&words, 33)
            .expect_err("byte length past capacity rejected");

        assert!(err.contains("exceeds word capacity"));
    }

    #[test]
    fn packed_program_codec_rejects_non_zero_padding() {
        let bytes = vec![0xaa; 31];
        let mut words = PackedProgramCodec::encode_words(&bytes);
        words[0] |= U256::from(1u64);

        let err = PackedProgramCodec::decode_words(&words, bytes.len())
            .expect_err("non-zero padding rejected");

        assert!(err.contains("non-zero padding"));
    }
}
