//! Typed payload layout for generated verifier artifacts.
//!
//! This is the small, local piece we borrow from the reusable-artifact style:
//! generated byte payloads should have one validated section map instead of
//! scattered offset arithmetic. The Solidity shape remains static and pinned.

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) enum PayloadSectionKind {
    Header,
    QuotientConstants,
    QuotientProgram,
    FixedCommitments,
    PermutationCommitments,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct PayloadSection {
    pub(crate) kind: PayloadSectionKind,
    pub(crate) word_offset: usize,
    pub(crate) word_len: usize,
}

impl PayloadSection {
    pub(crate) fn word_end(self) -> usize {
        self.word_offset + self.word_len
    }

    pub(crate) fn byte_offset(self) -> usize {
        self.word_offset * 0x20
    }

    pub(crate) fn byte_len(self) -> usize {
        self.word_len * 0x20
    }
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub(crate) struct VkPayloadLayout {
    sections: Vec<PayloadSection>,
    cursor_words: usize,
}

impl VkPayloadLayout {
    pub(crate) fn new() -> Self {
        Self::default()
    }

    pub(crate) fn for_vk(
        header_words: usize,
        quotient_const_words: usize,
        quotient_program_words: usize,
        fixed_commitments: usize,
        permutation_commitments: usize,
    ) -> Result<Self, String> {
        let mut layout = Self::new();
        layout.reserve(PayloadSectionKind::Header, header_words)?;
        layout.reserve(PayloadSectionKind::QuotientConstants, quotient_const_words)?;
        layout.reserve(PayloadSectionKind::QuotientProgram, quotient_program_words)?;
        layout.reserve_g1(PayloadSectionKind::FixedCommitments, fixed_commitments)?;
        layout.reserve_g1(
            PayloadSectionKind::PermutationCommitments,
            permutation_commitments,
        )?;
        layout.validate()?;
        Ok(layout)
    }

    pub(crate) fn reserve(
        &mut self,
        kind: PayloadSectionKind,
        word_len: usize,
    ) -> Result<PayloadSection, String> {
        if self.sections.iter().any(|section| section.kind == kind) {
            return Err(format!("duplicate VK payload section: {kind:?}"));
        }

        let section = PayloadSection {
            kind,
            word_offset: self.cursor_words,
            word_len,
        };
        self.cursor_words += word_len;
        self.sections.push(section);
        Ok(section)
    }

    pub(crate) fn reserve_g1(
        &mut self,
        kind: PayloadSectionKind,
        commitments: usize,
    ) -> Result<PayloadSection, String> {
        self.reserve(kind, commitments * 4)
    }

    pub(crate) fn section(&self, kind: PayloadSectionKind) -> Option<PayloadSection> {
        self.sections
            .iter()
            .copied()
            .find(|section| section.kind == kind)
    }

    pub(crate) fn require_section(
        &self,
        kind: PayloadSectionKind,
    ) -> Result<PayloadSection, String> {
        self.section(kind)
            .ok_or_else(|| format!("missing VK payload section: {kind:?}"))
    }

    pub(crate) fn word_offset(&self, kind: PayloadSectionKind) -> Result<usize, String> {
        Ok(self.require_section(kind)?.word_offset)
    }

    pub(crate) fn word_len(&self, kind: PayloadSectionKind) -> Result<usize, String> {
        Ok(self.require_section(kind)?.word_len)
    }

    pub(crate) fn byte_offset(&self, kind: PayloadSectionKind) -> Result<usize, String> {
        Ok(self.require_section(kind)?.byte_offset())
    }

    pub(crate) fn byte_len(&self, kind: PayloadSectionKind) -> Result<usize, String> {
        Ok(self.require_section(kind)?.byte_len())
    }

    pub(crate) fn total_words(&self) -> usize {
        self.cursor_words
    }

    pub(crate) fn total_bytes(&self) -> usize {
        self.total_words() * 0x20
    }

    pub(crate) fn validate(&self) -> Result<(), String> {
        let mut cursor = 0usize;
        for section in &self.sections {
            if section.word_offset != cursor {
                return Err(format!(
                    "VK payload section {:?} starts at {:#x}, expected {cursor:#x}",
                    section.kind, section.word_offset
                ));
            }
            cursor = section.word_end();
        }
        if cursor != self.cursor_words {
            return Err(format!(
                "VK payload cursor mismatch: sections end at {cursor:#x}, cursor is {:#x}",
                self.cursor_words
            ));
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::{PayloadSectionKind, VkPayloadLayout};

    #[test]
    fn vk_payload_layout_reserves_monotonic_sections() {
        let layout = VkPayloadLayout::for_vk(31, 3, 5, 7, 2).unwrap();

        assert_eq!(layout.word_offset(PayloadSectionKind::Header).unwrap(), 0);
        assert_eq!(
            layout
                .word_offset(PayloadSectionKind::QuotientConstants)
                .unwrap(),
            31
        );
        assert_eq!(
            layout
                .word_offset(PayloadSectionKind::QuotientProgram)
                .unwrap(),
            34
        );
        assert_eq!(
            layout
                .word_offset(PayloadSectionKind::FixedCommitments)
                .unwrap(),
            39
        );
        assert_eq!(
            layout
                .word_offset(PayloadSectionKind::PermutationCommitments)
                .unwrap(),
            67
        );
        assert_eq!(layout.total_words(), 75);
        assert_eq!(
            layout
                .byte_offset(PayloadSectionKind::FixedCommitments)
                .unwrap(),
            39 * 0x20
        );
        assert_eq!(
            layout
                .byte_len(PayloadSectionKind::PermutationCommitments)
                .unwrap(),
            2 * 0x80
        );
    }

    #[test]
    fn vk_payload_layout_rejects_duplicate_sections() {
        let mut layout = VkPayloadLayout::new();
        layout.reserve(PayloadSectionKind::Header, 31).unwrap();
        let err = layout
            .reserve(PayloadSectionKind::Header, 1)
            .expect_err("duplicate section rejected");

        assert!(err.contains("duplicate VK payload section"));
    }
}
