#!/usr/bin/env python3
"""Extract Rust comments from the sibling Midfall proofs crate.

The generated corpus is intentionally source-indexed rather than rewritten into
local code. That gives this verifier repo a complete, reviewable copy of the
upstream explanatory comments while letting local inline comments stay focused
on behavior that is actually ported into Solidity/Yul.
"""

from __future__ import annotations

import argparse
import dataclasses
import pathlib
import re
import subprocess
import sys
from typing import Iterable


DEFAULT_SOURCE = pathlib.Path("../midfall/proofs/src")
DEFAULT_OUTPUT = pathlib.Path("docs/MIDFALL_PROOFS_COMMENT_CORPUS.md")
COMMENT_RE = re.compile(r"^(?P<indent>\s*)//(?P<marker>!|/)?(?P<body>.*)$")


@dataclasses.dataclass(frozen=True)
class CommentBlock:
    path: pathlib.Path
    start: int
    end: int
    kind: str
    lines: tuple[str, ...]


def git_value(args: list[str], cwd: pathlib.Path) -> str:
    try:
        return subprocess.check_output(
            ["git", *args],
            cwd=cwd,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def git_root(path: pathlib.Path) -> pathlib.Path:
    value = git_value(["rev-parse", "--show-toplevel"], path)
    return pathlib.Path(value) if value != "unknown" else path


def comment_kind(marker: str | None) -> str:
    if marker == "!":
        return "module-doc"
    if marker == "/":
        return "item-doc"
    return "line"


def clean_body(body: str) -> str:
    return body[1:] if body.startswith(" ") else body


def extract_file(path: pathlib.Path, rel: pathlib.Path) -> list[CommentBlock]:
    blocks: list[CommentBlock] = []
    active_start: int | None = None
    active_end = 0
    active_kind: str | None = None
    active_lines: list[str] = []

    def flush() -> None:
        nonlocal active_start, active_end, active_kind, active_lines
        if active_start is not None and active_kind is not None:
            blocks.append(
                CommentBlock(
                    path=rel,
                    start=active_start,
                    end=active_end,
                    kind=active_kind,
                    lines=tuple(active_lines),
                )
            )
        active_start = None
        active_end = 0
        active_kind = None
        active_lines = []

    for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        match = COMMENT_RE.match(line)
        if match is None:
            flush()
            continue

        kind = comment_kind(match.group("marker"))
        body = clean_body(match.group("body"))
        if active_start is None:
            active_start = lineno
            active_kind = kind
            active_lines = [body]
        elif active_kind == kind and active_end + 1 == lineno:
            active_lines.append(body)
        else:
            flush()
            active_start = lineno
            active_kind = kind
            active_lines = [body]
        active_end = lineno

    flush()
    return blocks


def source_files(source: pathlib.Path) -> list[pathlib.Path]:
    return sorted(source.resolve().rglob("*.rs"))


def extract_comments(source: pathlib.Path) -> list[CommentBlock]:
    source = source.resolve()
    blocks: list[CommentBlock] = []
    for path in source_files(source):
        rel = path.relative_to(source)
        blocks.extend(extract_file(path, rel))
    return blocks


def fence_for(lines: Iterable[str]) -> str:
    max_ticks = 2
    for line in lines:
        for match in re.finditer(r"`+", line):
            max_ticks = max(max_ticks, len(match.group(0)))
    return "`" * (max_ticks + 1)


def render(source: pathlib.Path, blocks: list[CommentBlock]) -> str:
    source = source.resolve()
    root = git_root(source)
    commit = git_value(["rev-parse", "HEAD"], root)
    status = git_value(["status", "--short"], root)
    total_file_count = len(source_files(source))
    file_count = len({block.path for block in blocks})
    line_count = sum(len(block.lines) for block in blocks)

    out: list[str] = [
        "# Midfall Proofs Comment Corpus",
        "",
        "Generated by `scripts/extract_midfall_comments.py` from upstream Rust comments.",
        "This file preserves the source comments verbatim by path and line span;",
        "verifier-relevant material is adapted inline in this repository's source",
        "and templates.",
        "",
        "## Source",
        "",
        f"- Source root: `{source}`",
        f"- Git root: `{root}`",
        f"- Git commit: `{commit}`",
        f"- Git status at extraction: `{status or 'clean'}`",
        f"- Rust source files: `{total_file_count}`",
        f"- Rust files with comments: `{file_count}`",
        f"- Comment blocks: `{len(blocks)}`",
        f"- Comment lines: `{line_count}`",
        "",
        "## License And Attribution",
        "",
        "The comments below originate from the sibling Midfall `proofs` crate.",
        "That crate ships Apache-2.0 and MIT license files, and some LogUp",
        "files carry explicit Apache-2.0 SPDX/license headers. Preserve those",
        "notices when copying or adapting comments into source files.",
        "",
    ]

    current_path: pathlib.Path | None = None
    for block in blocks:
        if current_path != block.path:
            current_path = block.path
            out.extend(["", f"## `{block.path}`", ""])

        span = f"L{block.start}" if block.start == block.end else f"L{block.start}-L{block.end}"
        out.extend([f"### `{block.path}:{span}` ({block.kind})", ""])
        fence = fence_for(block.lines)
        out.append(f"{fence}text")
        out.extend(block.lines)
        out.append(fence)
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=pathlib.Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if output differs")
    parser.add_argument("--write", action="store_true", help="write the generated corpus")
    args = parser.parse_args()

    if args.check == args.write:
        parser.error("choose exactly one of --check or --write")

    source = args.source.resolve()
    if not source.is_dir():
        print(f"source directory not found: {source}", file=sys.stderr)
        return 2

    rendered = render(source, extract_comments(source))
    output = args.output.resolve()

    if args.write:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered, encoding="utf-8")
        print(f"wrote {output}")
        return 0

    current = output.read_text(encoding="utf-8") if output.exists() else ""
    if current != rendered:
        print(
            f"{output} is stale; run `scripts/extract_midfall_comments.py --write`",
            file=sys.stderr,
        )
        return 1

    print(f"{output} is up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
