use crate::codegen::util::{fe_to_u256, to_u256_be_bytes};
use ff::PrimeField;
use itertools::chain;

/// Function signature of `verifyProof(bytes,uint256[])`.
pub const FN_SIG_VERIFY_PROOF: [u8; 4] = [0x1e, 0x8e, 0x1e, 0x13];

/// Encode proof into calldata to invoke `Halo2Verifier.verifyProof`.
///
/// Generic over the instance scalar so the same helper handles both BN254
/// and BLS12-381 instances (both fields have a 32-byte `Repr`, which is
/// what the Solidity verifier reads from calldata).
pub fn encode_calldata<F>(proof: &[u8], instances: &[F]) -> Vec<u8>
where
    F: PrimeField,
    F::Repr: AsRef<[u8]>,
{
    let offset = 0x40;
    let num_instances = instances.len();
    chain![
        FN_SIG_VERIFY_PROOF,                           // function signature
        to_u256_be_bytes(offset),                      // offset of proof
        to_u256_be_bytes(offset + 0x20 + proof.len()), // offset of instances
        to_u256_be_bytes(proof.len()),                 // length of proof
        proof.iter().cloned(),                         // proof
        to_u256_be_bytes(num_instances),               // length of instances
        instances
            .iter()
            .map(fe_to_u256::<F>)
            .flat_map(to_u256_be_bytes), // instances
    ]
    .collect()
}

#[cfg(any(test, feature = "evm"))]
#[allow(dead_code)]
pub(crate) mod test {
    pub use revm;
    use revm::{
        db::InMemoryDB,
        primitives::{Address, ExecutionResult, Log, Output, SpecId, TxKind},
        Evm as RevmEvm,
    };
    use ruint::aliases::U256;
    use sha3::{Digest, Keccak256};
    use std::{
        env,
        fmt::{self, Debug, Formatter},
        io::{self, Write},
        process::{Command, Stdio},
        str,
    };

    /// Default `--optimize-runs` value used by `compile_solidity`.
    ///
    /// Pre-Step 5 the verifier inlined `decompress_g1` at 21 sites, and
    /// running the optimizer with `runs=200` blew past EIP-170's 24 kB
    /// contract limit; we forced `runs=1` to keep the helpers shared.
    /// After Step 5 dropped the on-chain decompression entirely, that
    /// constraint went away and `runs=200` is now both safe (the
    /// rendered bytecode comfortably fits under 24 kB) and significantly
    /// cheaper at runtime — the optimizer can deduplicate
    /// `common_uncompressed_g1`, `scalar_inv`, the `ec_*` helpers, and
    /// hoist `mload` traffic in the gate evaluator.
    /// Audit item #7 / OPTIMISATION.md "A".
    pub const DEFAULT_OPTIMIZE_RUNS: u32 = 200;
    /// Exact solc compiler identity used for reproducible generated bytecode.
    ///
    /// The platform suffix printed by `solc --version` can differ between
    /// builds of the same compiler commit, so the gate pins the semantic
    /// version and upstream commit.
    pub const PINNED_SOLC_VERSION: &str = "0.8.30+commit.73712a01";

    /// Return the configured solc executable path.
    pub fn solc_command() -> String {
        env::var("SOLC").unwrap_or_else(|_| "solc".to_string())
    }

    /// Return the `Version:` field from `solc --version`.
    pub fn solc_version() -> io::Result<String> {
        let solc = solc_command();
        let output = Command::new(&solc).arg("--version").output()?;
        if !output.status.success() {
            return Err(io::Error::other(format!(
                "{solc} --version exited with {}",
                output.status
            )));
        }
        let stdout = str::from_utf8(&output.stdout)
            .map_err(|err| io::Error::new(io::ErrorKind::InvalidData, err))?;
        stdout
            .lines()
            .find_map(|line| line.strip_prefix("Version: "))
            .map(str::to_owned)
            .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidData, "missing solc Version line"))
    }

    /// True when the configured solc executable matches the pinned compiler
    /// version/commit.
    pub fn pinned_solc_available() -> bool {
        match solc_version() {
            Ok(version) if version.starts_with(PINNED_SOLC_VERSION) => true,
            Ok(version) => {
                eprintln!(
                    "configured solc version {version} does not match pinned {PINNED_SOLC_VERSION}"
                );
                false
            }
            Err(err) => {
                eprintln!("pinned solc unavailable: {err}");
                false
            }
        }
    }

    fn require_pinned_solc() -> String {
        let solc = solc_command();
        let version = solc_version()
            .unwrap_or_else(|err| panic!("Command '{solc}' not found or unusable: {err}"));
        assert!(
            version.starts_with(PINNED_SOLC_VERSION),
            "configured solc `{solc}` has version `{version}`, expected `{PINNED_SOLC_VERSION}`"
        );
        solc
    }

    /// Compile solidity with `--via-ir`, targeting Cancun bytecode (the
    /// embedded revm runner is set up for the Prague hard fork which
    /// supersedes Cancun + adds EIP-2537), then return creation bytecode.
    ///
    /// Honors the `SOLC_OPTIMIZE_RUNS` environment variable for ad-hoc
    /// A/B measurement; if unset, uses `DEFAULT_OPTIMIZE_RUNS`.
    ///
    /// # Panics
    /// Panics if executable `solc` can not be found, does not match
    /// [`PINNED_SOLC_VERSION`], or compilation fails.
    pub fn compile_solidity(solidity: impl AsRef<[u8]>) -> Vec<u8> {
        let runs: u32 = std::env::var("SOLC_OPTIMIZE_RUNS")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(DEFAULT_OPTIMIZE_RUNS);
        compile_solidity_with_runs(solidity, runs)
    }

    /// Like `compile_solidity` but with an explicit `--optimize-runs`
    /// value. Useful for benchmarking the optimizer's runtime/code-size
    /// tradeoff. Omits CBOR metadata so reported bytecode sizes reflect
    /// executable verifier code rather than compiler provenance.
    ///
    /// # Panics
    /// Panics if executable `solc` can not be found, does not match
    /// [`PINNED_SOLC_VERSION`], or compilation fails.
    pub fn compile_solidity_with_runs(solidity: impl AsRef<[u8]>, runs: u32) -> Vec<u8> {
        let runs_str = runs.to_string();
        let solc = require_pinned_solc();
        let mut process = match Command::new(&solc)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .arg("--bin")
            .arg("--optimize")
            .arg("--optimize-runs")
            .arg(&runs_str)
            .arg("--via-ir")
            .arg("--evm-version")
            .arg("cancun")
            .arg("--no-cbor-metadata")
            .arg("-")
            .spawn()
        {
            Ok(process) => process,
            Err(err) if err.kind() == io::ErrorKind::NotFound => {
                panic!("Command '{solc}' not found");
            }
            Err(err) => {
                panic!("Failed to spawn process with command '{solc}':\n{err}");
            }
        };
        process
            .stdin
            .take()
            .unwrap()
            .write_all(solidity.as_ref())
            .unwrap();
        let output = process.wait_with_output().unwrap();
        let stdout = str::from_utf8(&output.stdout).unwrap();
        if let Some(binary) = find_binary(stdout) {
            binary
        } else {
            panic!(
                "Compilation fails:\n{}",
                str::from_utf8(&output.stderr).unwrap()
            )
        }
    }

    fn find_binary(stdout: &str) -> Option<Vec<u8>> {
        let start = stdout.find("Binary:")? + 8;
        Some(hex::decode(&stdout[start..stdout.len() - 1]).unwrap())
    }

    /// Result of a non-panicking EVM call. Mirrors revm's
    /// `ExecutionResult` shape but flattens to what test/example code
    /// usually wants: gas, optional output bytes, optional revert
    /// payload, and any emitted logs.
    #[derive(Debug)]
    pub enum CallOutcome {
        /// The call returned normally.
        Success {
            /// Gas consumed by the call.
            gas_used: u64,
            /// Return-data bytes copied from the EVM.
            output: Vec<u8>,
            /// Logs emitted during the call.
            logs: Vec<Log>,
        },
        /// The call hit a `revert` opcode.
        Revert {
            /// Gas consumed before the revert.
            gas_used: u64,
            /// Revert payload bytes (often empty for solc-generated
            /// `revert(0, 0)` paths).
            output: Vec<u8>,
        },
        /// The call halted (out-of-gas, invalid opcode, etc.).
        Halt {
            /// Gas consumed before the halt.
            gas_used: u64,
            /// Debug string identifying the halt reason.
            reason: String,
        },
    }

    /// In-process EVM runner pinned to `SpecId::PRAGUE` so that the
    /// EIP-2537 BLS12-381 precompiles (`0x0b`/`0x0c`/`0x0d`/`0x0e`/`0x0f`)
    /// are routed to revm's bundled implementations. The runner keeps an
    /// `InMemoryDB` across calls so tests can deploy once and call many
    /// times.
    #[derive(Default)]
    pub struct Evm {
        db: InMemoryDB,
    }

    impl Debug for Evm {
        fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
            f.debug_struct("Evm").finish_non_exhaustive()
        }
    }

    impl Evm {
        /// Return code_size of given address.
        ///
        /// # Panics
        /// Panics if given address doesn't have bytecode.
        pub fn code_size(&mut self, address: Address) -> usize {
            self.db.accounts[&address]
                .info
                .code
                .as_ref()
                .map(|c| c.len())
                .unwrap_or(0)
        }

        /// Return the Keccak256 hash of deployed runtime bytecode at `address`.
        ///
        /// # Panics
        /// Panics if given address doesn't have bytecode.
        pub fn code_hash(&mut self, address: Address) -> U256 {
            let code = self.db.accounts[&address]
                .info
                .code
                .as_ref()
                .expect("address must have bytecode")
                .original_bytes();
            let digest: [u8; 32] = Keccak256::digest(&code).into();
            U256::from_be_bytes(digest)
        }

        /// Apply create transaction with given `bytecode` as creation bytecode.
        /// Return created `address`.
        ///
        /// # Panics
        /// Panics if execution reverts or halts unexpectedly.
        pub fn create(&mut self, bytecode: Vec<u8>) -> Address {
            let (_, output, _) = self.run_tx(TxKind::Create, bytecode);
            match output {
                Output::Create(_, Some(address)) => address,
                _ => unreachable!("expected create output, got {output:?}"),
            }
        }

        /// Apply create transaction with an address constructor argument appended to creation
        /// bytecode and return created `address`.
        pub fn create_with_address_arg(
            &mut self,
            mut bytecode: Vec<u8>,
            address_arg: Address,
        ) -> Address {
            bytecode.extend_from_slice(
                &U256::try_from_be_slice(address_arg.as_slice())
                    .unwrap()
                    .to_be_bytes::<0x20>(),
            );
            self.create(bytecode)
        }

        /// Apply create transaction with two address constructor arguments
        /// appended to creation bytecode and return created `address`.
        pub fn create_with_two_address_args(
            &mut self,
            mut bytecode: Vec<u8>,
            first_address_arg: Address,
            second_address_arg: Address,
        ) -> Address {
            for address in [first_address_arg, second_address_arg] {
                bytecode.extend_from_slice(
                    &U256::try_from_be_slice(address.as_slice())
                        .unwrap()
                        .to_be_bytes::<0x20>(),
                );
            }
            self.create(bytecode)
        }

        /// Apply call transaction to given `address` with `calldata`.
        /// Returns `gas_used` and `return_data`.
        ///
        /// # Panics
        /// Panics if execution reverts or halts unexpectedly.
        pub fn call(&mut self, address: Address, calldata: Vec<u8>) -> (u64, Vec<u8>) {
            let (gas_used, output, _) = self.run_tx(TxKind::Call(address), calldata);
            match output {
                Output::Call(output) => (gas_used, output.into()),
                _ => unreachable!("expected call output, got {output:?}"),
            }
        }

        /// Apply call transaction without panicking on revert/halt.
        /// Useful for fuzzing or trace-driven debugging where we want to
        /// observe failures rather than abort the run.
        pub fn try_call(&mut self, address: Address, calldata: Vec<u8>) -> CallOutcome {
            self.try_call_with_gas(address, calldata, 50_000_000)
        }

        /// Like [`Self::try_call`] but with a caller-controlled gas ceiling.
        /// Necessary for very wide circuits (e.g. the IVC verifier at
        /// k = 19 with ~20+ advice columns) whose verifier doesn't fit
        /// within the default 50M cap during dev.
        pub fn try_call_with_gas(
            &mut self,
            address: Address,
            calldata: Vec<u8>,
            gas_limit: u64,
        ) -> CallOutcome {
            let db = std::mem::take(&mut self.db);
            let mut evm = RevmEvm::builder()
                .with_db(db)
                .with_spec_id(SpecId::PRAGUE)
                .modify_cfg_env(|cfg| {
                    cfg.limit_contract_code_size = Some(usize::MAX);
                })
                .modify_tx_env(|tx| {
                    tx.gas_limit = gas_limit;
                    tx.transact_to = TxKind::Call(address);
                    tx.data = calldata.into();
                })
                .build();
            let result = evm.transact_commit().unwrap();
            self.db = std::mem::take(&mut evm.context.evm.db);
            match result {
                ExecutionResult::Success {
                    gas_used,
                    output,
                    logs,
                    ..
                } => CallOutcome::Success {
                    gas_used,
                    output: match output {
                        Output::Call(o) => o.into(),
                        _ => unreachable!(),
                    },
                    logs,
                },
                ExecutionResult::Revert { gas_used, output } => CallOutcome::Revert {
                    gas_used,
                    output: output.into(),
                },
                ExecutionResult::Halt { reason, gas_used } => CallOutcome::Halt {
                    gas_used,
                    reason: format!("{reason:?}"),
                },
            }
        }

        /// Apply call transaction and return gas, return data, and emitted logs.
        pub fn call_with_logs(
            &mut self,
            address: Address,
            calldata: Vec<u8>,
        ) -> (u64, Vec<u8>, Vec<Log>) {
            let (gas_used, output, logs) = self.run_tx(TxKind::Call(address), calldata);
            match output {
                Output::Call(output) => (gas_used, output.into(), logs),
                _ => unreachable!("expected call output, got {output:?}"),
            }
        }

        /// Build a Prague-spec EVM around the in-memory db, run the
        /// configured transaction, commit, then unwrap the success result.
        fn run_tx(&mut self, transact_to: TxKind, data: Vec<u8>) -> (u64, Output, Vec<Log>) {
            // Take the db out so we can hand it to the builder, then put it
            // back after the call.
            let db = std::mem::take(&mut self.db);
            let mut evm = RevmEvm::builder()
                .with_db(db)
                .with_spec_id(SpecId::PRAGUE)
                .modify_cfg_env(|cfg| {
                    // Lift the EIP-170 contract size cap. The full
                    // BLS12-381 verifier (with inline `decompress_g1`
                    // calls per commitment) compiles to ~25 kB of
                    // bytecode, which exceeds the 24 kB mainnet
                    // limit; for in-process tests this is fine.
                    cfg.limit_contract_code_size = Some(usize::MAX);
                })
                .modify_tx_env(|tx| {
                    // Capped at 50M gas so an infinite loop in the
                    // emitted Yul terminates promptly during dev
                    // rather than spinning revm indefinitely.
                    tx.gas_limit = 50_000_000;
                    tx.transact_to = transact_to;
                    tx.data = data.into();
                })
                .build();
            let result = evm.transact_commit().unwrap();
            // Recover the database for the next call. revm 19 stores the
            // db deep inside `evm.context.evm.db`; the simplest way to get
            // it back without moving fields out of `EvmContext` (which
            // holds non-Copy state) is to swap with a dummy default.
            self.db = std::mem::take(&mut evm.context.evm.db);
            match result {
                ExecutionResult::Success {
                    gas_used,
                    output,
                    logs,
                    ..
                } => {
                    if !logs.is_empty() {
                        println!("--- logs from {} ---", logs[0].address);
                        for (log_idx, log) in logs.iter().enumerate() {
                            println!("log#{log_idx}");
                            for (topic_idx, topic) in log.data.topics().iter().enumerate() {
                                println!("  topic{topic_idx}: {topic:?}");
                            }
                        }
                        println!("--- end ---");
                    }
                    (gas_used, output, logs)
                }
                ExecutionResult::Revert { gas_used, output } => {
                    panic!("Transaction reverts with gas_used {gas_used} and output 0x{output:x}")
                }
                ExecutionResult::Halt { reason, gas_used } => panic!(
                    "Transaction halts unexpectedly with gas_used {gas_used} and reason {reason:?}"
                ),
            }
        }
    }
}
